export const BOT_TOKEN = process.env.BOT_TOKEN;
export const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;
export const WEBAPP_URL = process.env.WEBAPP_URL || 'https://paywall-tg.vercel.app';
export const PLATFORM_FEE_PERCENT = 5; // 5% commission
export const MIN_PRICE_STARS = 1;
export const MAX_PRICE_STARS = 10000;
export const MAX_TITLE_LENGTH = 100;
export const MAX_DESCRIPTION_LENGTH = 300;
export const MAX_CONTENT_LENGTH = 3800;
